baseurl = "https://whatsuptoyou.github.io"
languageCode = "en-us"
title = "npf.io"
theme = "hyde"
copyright = "hugo"
disableKinds = ["RSS"]

[Author]
	name = "che"

[Permalinks]
	blog = "/:year/:month/:filename/"
	code = "/:filename/"

[Taxonomies]
	tag = "tags"
	series = "series"
	series-desc = "series-desc"

[params]
	description = "code by Nate Finch"
	twitter = "https://twitter.com/natethefinch"
	github = "https://github.com/natefinch"
	gplus = "https://plus.google.com/+NateFinch"
	disqus = "npfio"
	mainImage = "/moose.svg"

